version: "3.9"
services:

  # BBDD PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: tenpo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tenpo-net

  # Redis
  redis:
    image: redis:7-alpine
    container_name: tenpo-redis
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tenpo-net

  # API principal
  tenpo-api:
    image: ${DOCKER_IMAGE:-martinbuldain/tenpo-challenge:latest}
    container_name: tenpo-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_URL:      jdbc:postgresql://postgres:5432/${DB_NAME}
      R2DBC_URL:   r2dbc:postgresql://postgres:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      EXTERNAL_SERVICE_URL: ${EXTERNAL_SERVICE_URL}

      JAVA_OPTS: "${JAVA_OPTS}"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    networks:
      - tenpo-net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  tenpo-net:
    driver: bridge
